site_name: Python для мережевих інженерів

# Repository
#repo_name: natenka/pyneng.io
#repo_url: https://github.com/natenka/pyneng.io

theme:
  name: material
  language: uk
  icon:
    logo: material/book-open-outline
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - navigation.top
    # - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode


# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
#pip install mkdocs-pdf-export-plugin
# pdf export
#  - pdf-export:
#      combined: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://pyneng.io/course/slack/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCKTDqzgELjWO7wseP-OHNew
    - icon: fontawesome/brands/github
      link: https://github.com/natenka
    - icon: fontawesome/brands/telegram
      link: https://t.me/pynenguk


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - " ": index.md
  - Книга:
    - book/index.md
    - book/links.md
    - Основи Python:
      - 1. Підготовка до роботи:
        - book/01_intro/index.md
        - book/01_intro/work_env.md
        - book/01_intro/os_and_editor.md
        - book/01_intro/pip.md
        - book/01_intro/venv.md
        - book/01_intro/check_python.md
        - book/01_intro/further_reading.md
      - 2. Використання Git та GitHub:
        - book/02_git_github/index.md
        - book/02_git_github/git_basics.md
        - book/02_git_github/git_basics_bash_status.md
        - book/02_git_github/git_basics_commands.md
        - book/02_git_github/git_basics_additional.md
        - book/02_git_github/git_github_auth.md
        - book/02_git_github/git_github_changes.md
        - book/02_git_github/pyneng_github.md
        - book/02_git_github/further_reading.md
      - 3. Початок роботи з Python:
        - book/03_start/index.md
        - book/03_start/syntax.md
        - book/03_start/ipython.md
        - book/03_start/ipython_magic.md
        - book/03_start/variables.md
      - 4. Типи даних у Python:
        - book/04_data_structures/index.md
        - book/04_data_structures/numbers.md
        - Рядки (Strings):
          - book/04_data_structures/string/index.md
          - book/04_data_structures/string/methods.md
          - book/04_data_structures/string/literal_concatenation.md
        - Список (List):
          - book/04_data_structures/list/index.md
          - book/04_data_structures/list/methods.md
        - Словник (Dictionary):
          - book/04_data_structures/dict/index.md
          - book/04_data_structures/dict/methods.md
          - book/04_data_structures/dict/create.md
        - book/04_data_structures/tuple.md
        - book/04_data_structures/set.md
        - book/04_data_structures/boolean.md
        - book/04_data_structures/string_format.md
        - book/04_data_structures/convert_type.md
        - book/04_data_structures/check_type.md
        - book/04_data_structures/method_chaining.md
        - book/04_data_structures/sorting.md
        - book/04_data_structures/further_reading.md
  - Курс:
    - course/index.md
    - Лекції:
      - course/schedule.md
      - course/theory.md
      - course/theory-details.md
    - Теми:
      - course/topics/00-preparation.md
      - course/topics/01-course-env.md
      - course/topics/02-git-github-tasks.md
    - Корисні посилання:
      - course/schedule-tasks.md
      - course/calendar.md
      - course/slack.md
      - course/links.md
  - Завдання:
    - tasks/index.md
    - tasks/pyneng.md
    # - tasks/pyneng-output.md
    - tasks/task-topic-table.md
    - Підготовка вм/хоста:
      - Linux: tasks/linux.md
      - Windows: tasks/windows.md
      - tasks/windows-gotchas.md
    - Редактори:
      - tasks/editors/index.md
      - tasks/editors/prepare.md
      - tasks/editors/thonny.md
      - tasks/editors/vim.md
  - Запитання:
    - quiz/index.md
