[build]
    command = "pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git9.1.21-insiders-4.39.0 mkdocs-git-revision-date-localized-plugin && mkdocs build"
    publish = "site"
