# Plugins
plugins:
  - blog
  - search
  - git-revision-date-localized:
      enable_creation_date: true
#- with-pdf:
  - extra-sass
  - with-pdf:
      ordered_chapter_level: 0
      output_path: site/pdf/document.pdf
      author: Nataliia Samoilenko
      toc_level: 3
      exclude_pages:
        - blog/
        - reference/
        - course/
      cover_subtitle: Книга, курс та завдання з основ Python
      # render_js: true
      # headless_chrome_path: chromium
